### ISSUE TITLE
Debian Stretch version

### ISSUE THREAD

**Issue by Shraa** [Fa1c0nSec/HadoopHADeploymentScript#2]
Could you please modify these scripts for Debian Stretch?

**Comment by Fa1c0nSec** [comment]
When I'm coding, in order to consider maximum compatibility, the operating system is limited to Ubuntu, but actually, this script is fully compatible with Debian Stretch. this script is designed for 1 master node named "MASTER1" and 2 compute node "MASTER2 & MASTER3"with High Availability enabled.  Multi-node support will be support in future.
How to use this script? here are instructions.
when you finished clone this scripts from github [command: git clone https://github.com/Fa1c0nSec/HadoopHADeploymentScript]
enter the "lib" directory, modify "installrc" file:

> \#GENERAL COMMON VARIABLES 
> HOST_NAME=master1                           // you can change master1's hostname to master1 with command [echo "master1" > /etc/hostname]
> MASTER1_IP=10.211.55.20                    //MASTER1 IP ADDRESS for common, modify with your environment
> MASTER2_IP=10.211.55.19                    //MASTER2 IP ADDRESS for common, modify with your environment
> MASTER3_IP=10.211.55.18                    //MASTER3 IP ADDRESS for common, modify with your environment
> 
> MASTER1_USRNAME=root                 // strongly recommend use 'root' account.
> MASTER2_USRNAME=root                 // strongly recommend use 'root' account.
> MASTER3_USRNAME=root                 // strongly recommend use 'root' account.
> 
> MASTER1_PWD=root                          // root account password.
> MASTER2_PWD=root                          // root account password.
> MASTER3_PWD=root                          // root account password.
> 
> INSTALLATION_PATH=/data/dev/                                  // default installation path, you can change to any directory.


when you finished with "installrc" file, you need to modify "hosts" file
> 127.0.0.1    localhost                                         // DO NOT MODIFY THIS LINE
> 127.0.1.1    Fa1c0n-MacBook-Pro                    // you can change this to any name you like, but this must be consistent in three nodes, or hadoop initialization will report fatal error.
> 
> \# The following lines are desirable for IPv6 capable hosts
> ::1     ip6-localhost ip6-loopback
> fe00::0 ip6-localnet
> ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
> ff02::2 ip6-allrouters
> 10.211.55.20    master1                           // master1 ip address.
> 10.211.55.19    master2                           // master2 ip address.
> 10.211.55.18    master3                           // master3 ip address.

when you finished modify this file, you would like run this script in debian os, delete 1 line in "etc/environment_setup.sh" file line 77, "fahda_fn_check_os_version".
and then back to directory contains "main.sh", and use command "scp" to make sure this folder is exist in three nodes, and you can install this script in three nodes in sametime. for example, master1 install JDK, meanwhile, master2 and master3 install JDK too.

**WARNING**: 
PLEASE MUST BE SURE INSTALL "4) ZooKeeper Installation" THREE NODES IN EXACTLY SAME TIME! WHEN ZOOKEEPER INSTALLATION FINISHED, SYSTEM REBOOT REQUIRED. AT THE END OF ZOOKEEPER INSTALLATION, IT WILL REBOOT 3 NODES TOGETHER. IF YOU ENTER 4 IN EXACTLY SAME TIME, 3 NODES WILL REBOOT TOGETHER, AND MOVE ON TO 5 TO CONTINUE INSTALLATION.
**WARNING**: 
OPTION 7) EXECUTE WHILE INSTALLTION ONLY ONCE! NORMAL HADOOP RUN DO NOT NEED TO INITIALIZE.  
**WARNING**: 
DO NOT USE "9) Data Directory Copy(DISABLED)", this will use scp command to transfer your data directory to other nodes, it will directly overwrite. so, DO NOT USE THIS OPTION.

Hadoop HA Start Order:
First, you must start ZooKeeper on three nodes, and you can use main.sh option 8 to start hadoop on one node, other nodes service will start automatically.

about "Hbase、Hive、Pig、Mahout、Spark、Storm、Kafka、......" automatically installation script will be finished in future, if you need. I am preparing for the graduate entrance examination, so I don’t have much time to write these installation script now. If you need it urgently, please contact me with ：
Email: i@fa1c0n.com

Thanks,
Fa1c0n
2018.07.31
